receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    send_batch_size: 1000
    timeout: 10s

exporters:
  # Prometheus 远程写入
  prometheusremotewrite:
    endpoint: "http://prometheus:9090/api/v1/write"
    namespace: app_metrics
  
  # Loki 日志
  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"

  
  # Tempo 追踪
  otlp:
    endpoint: "tempo:4317"
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheusremotewrite]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [loki]